//EXPORT ACTIONS FOR FETCHING SMURF INFORMATION
export const FETCHING_SMURF_START = "FETCH_SMURF START";
export const FETCHING_SMURF_SUCCESS = "FETCH_SMURF_SUCCESS";
export const FETCHING_SMURF_ERROR = "FETCH_DATA_ERROR";